name: Code Linting Check

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3

      - name: Install ESLint and eslint-config-next
        run: |
          npm install eslint@^8 eslint-config-next@14.2.15 --no-save

      - name: Run ESLint (no auto-fix)
        run: npx eslint .

      - name: Install Black and isort
        run: |
          pip install black isort

      - name: Run Black (Python formatter)
        run: |
          black . 

      - name: Run isort (Python import sorter)
        run: |
          isort .
